# Wazuh App Copyright (C) 2017, Wazuh Inc. (License GPLv2)
services:
  generator:
    image: wazuh/wazuh-certs-generator:0.0.3
    hostname: wazuh-certs-generator
    environment:
      - CERT_TOOL_VERSION=4.14
    volumes:
      - ./wazuh/certs/:/certificates/:z
      - ./wazuh/certs.yml:/config/certs.yml:ro,z
